### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by qcam** [qcam/saxy#5]
- [x] Binary parsing.
- [x] Stream parsing.
- [x] Process instruction (#6).
- [x] Simple form (#10).
- [x] Entity Reference (no external entity reference) (#8).
- [x] Stop/halt control (#7).
- [ ] XPath support (partial?).
- [x] XML Builder.

**Comment by qcam** [comment]
Closing in favor of milestone.
